# SPDX-FileCopyrightText: 2019-2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

on: [push, pull_request]

env:
  SPACK_REPO: spack/spack
  SPACK_BRANCH: develop

jobs:
  debian:
    runs-on: ubuntu-20.04
    container:
      image: debian:9
    strategy:
      fail-fast: false
      matrix:
        part: [1, 2]
    steps:
    - name: Install prerequisites
      run: |
          apt-get update -qq
          apt install -qq -y python3 python3-pip git curl
    - uses: actions/checkout@v2
    - name: Install spack
      uses: actions/checkout@v2
      with:
        repository: ${{ env.SPACK_REPO }}
        path: spack
        ref: ${{ env.SPACK_BRANCH }}
    - name: Package tests
      run: |
        . spack/share/spack/setup-env.sh
        spack install intel-oneapi-compilers
